apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "garage-controller.fullname" . }}-config
  labels:
    {{- include "garage-controller.labels" . | nindent 4 }}
data:
  garage_api_endpoint: {{ required "config.garageApiEndpoint is required" .Values.config.garageApiEndpoint | quote }}
  garage_s3_api_endpoint: {{ required "config.garageS3ApiEndpoint is required" .Values.config.garageS3ApiEndpoint | quote }}
