{{- if and (not .Values.existingSecret) .Values.apiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: garage-api-token
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: garage-storage-controller
type: Opaque
stringData:
  api-token: {{ .Values.apiToken | quote }}
{{- end }}
