name: Lint and run govulncheck

on:
  push:
    branches: ["main"]

jobs:
  lint_vuln_check:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.9.0
        continue-on-error: true

      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-package: ./...
